/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    container: {
      center: true,
      padding: { DEFAULT: '1.5rem', sm: '2rem', lg: '3rem', xl: '4rem' },
    },
    extend: {
      colors: {
        bg: { DEFAULT: "#FFFFFF", alt: "#F8FAFC", deep: "#F1F5F9" },
        surface: { DEFAULT: "#FFFFFF", alt: "#F8FAFC", hover: "#F1F5F9" },
        accent: { DEFAULT: "#2563EB", dark: "#1E40AF", light: "#3B82F6" },
        success: '#10B981',
        warning: '#F59E0B',
        primary: "#0F172A",
        secondary: "#475569",
        body: "#1F2937",
        border: "#E2E8F0",
        borderAlt: "#CBD5E1",
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'hero-desktop': ['64px', { lineHeight: '1.1' }],
        'hero-tablet': ['48px', { lineHeight: '1.1' }],
        'hero-mobile': ['36px', { lineHeight: '1.2' }],
        'hero-desc-desktop': ['18px', { lineHeight: '1.7' }],
        'hero-desc-mobile': ['16px', { lineHeight: '1.7' }],
        'section-title-desktop': ['40px', { lineHeight: '1.2' }],
        'section-title-tablet': ['36px', { lineHeight: '1.2' }],
        'section-title-mobile': ['30px', { lineHeight: '1.2' }],
        'section-label': ['13px', { lineHeight: '1.5', letterSpacing: '0.08em' }],
        'card-title-desktop': ['24px', { lineHeight: '1.3' }],
        'card-title-mobile': ['20px', { lineHeight: '1.3' }],
        'body-lg': ['16px', { lineHeight: '1.75' }],
        'body-md': ['15px', { lineHeight: '1.7' }],
        'body-sm': ['14px', { lineHeight: '1.6' }],
        'metadata': ['13px', { lineHeight: '1.5' }],
        'job-title': ['24px', { lineHeight: '1.3' }],
        'company': ['18px', { lineHeight: '1.4' }],
        'competency-title': ['20px', { lineHeight: '1.3' }],
        'category-title': ['20px', { lineHeight: '1.3' }],
        'tech-tag': ['15px', { lineHeight: '1.5' }],
        'cta-desktop': ['48px', { lineHeight: '1.1' }],
        'cta-mobile': ['32px', { lineHeight: '1.2' }],
      },
      fontWeight: { normal: 400, medium: 500, semibold: 600, bold: 700, extrabold: 800 },
      boxShadow: {
        soft: '0 4px 6px -1px rgba(0, 0, 0, 0.05)',
        card: '0 1px 3px 0 rgba(0, 0, 0, 0.05)',
        elegant: '0 10px 15px -3px rgba(0, 0, 0, 0.05)',
      },
    },
  },
  plugins: [],
}